"""empty message

Revision ID: 60c31b9ed078
Revises: e76262edc956
Create Date: 2020-12-20 22:08:54.734122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c31b9ed078'
down_revision = 'e76262edc956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    op.drop_constraint('todos_todoList_id_fkey', 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    op.drop_column('todos', 'todoList_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('todoList_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key('todos_todoList_id_fkey', 'todos', 'todolists', ['todoList_id'], ['id'])
    op.drop_column('todos', 'list_id')
    # ### end Alembic commands ###
